name: course_motobike_cs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  d_session: ^0.0.3
  dotted_line: ^3.2.2
  extended_image: ^8.2.1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.5
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
